version: '3.0'

volumes:
    prometheus_data: {}
    grafana_data: {}
    alertmanager_data: {}

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--query.lookback-delta=90m'
    ports:
      - "9090:9090"
    restart: unless-stopped
  influxdb:
    image: influxdb:1.8.2
    container_name: influxdb
    volumes:
      - /path/to/docker-influxdb/config-folder:/var/lib/influxdb
    restart: unless-stopped
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - alertmanager_data:/alertmanager
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    restart: unless-stopped
  karma:
    image: lmierzwa/karma:v0.68
    container_name: karma
    environment:
      - ALERTMANAGER_URI=http://alertmanager:9093
    ports:
      - 8080:8080
    restart: unless-stopped
  
  # Exporters

  blackbox:
    image: quay.io/prometheus/blackbox-exporter:v0.17.0
    container_name: blackbox
    volumes:
      - ./blackbox/:/etc/blackboxexporter/
    command:
      - '--config.file=etc/blackboxexporter/config.yml'
    dns: 1.1.1.1
    restart: unless-stopped
  nodeexporter:
    image: quay.io/prometheus/node-exporter:v1.0.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    restart: unless-stopped
  piholeexporter:
    image: ekofr/pihole-exporter:0.0.9
    container_name: piholeexporter
    environment:
      - PIHOLE_HOSTNAME=192.168.1.2
      - PIHOLE_PASSWORD=mypassword
      - INTERVAL=30s
      - PORT=9617
    restart: unless-stopped
  speedtestexporter:
    image: miguelndecarvalho/docker-speedtest_exporter
    container_name: speedtestexporter
    restart: unless-stopped
  varken:
    image: boerderij/varken
    container_name: varken
    environment:
      - TZ=America/Chicago
      - VRKN_GLOBAL_SONARR_SERVER_IDS=1
      - VRKN_GLOBAL_RADARR_SERVER_IDS=1
      - VRKN_GLOBAL_TAUTULLI_SERVER_IDS=1
      - VRKN_GLOBAL_OMBI_SERVER_IDS=1
      - VRKN_GLOBAL_MAXMIND_LICENSE_KEY=xxxxxxxxxxxxxxxx
      - VRKN_INFLUXDB_URL=influxdb.domain.tld
      - VRKN_INFLUXDB_PORT=8086
      - VRKN_INFLUXDB_SSL=false
      - VRKN_INFLUXDB_VERIFY_SSL=false
      - VRKN_INFLUXDB_USERNAME=root
      - VRKN_INFLUXDB_PASSWORD=root
      - VRKN_TAUTULLI_1_URL=tautulli.domain.tld:8181
      - VRKN_TAUTULLI_1_FALLBACK_IP=1.1.1.1
      - VRKN_TAUTULLI_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_TAUTULLI_1_SSL=false
      - VRKN_TAUTULLI_1_VERIFY_SSL=false
      - VRKN_TAUTULLI_1_GET_ACTIVITY=true
      - VRKN_TAUTULLI_1_GET_ACTIVITY_RUN_SECONDS=30
      - VRKN_TAUTULLI_1_GET_STATS=true
      - VRKN_TAUTULLI_1_GET_STATS_RUN_SECONDS=3600
      - VRKN_SONARR_1_URL=sonarr1.domain.tld:8989
      - VRKN_SONARR_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_SONARR_1_SSL=false
      - VRKN_SONARR_1_VERIFY_SSL=false
      - VRKN_SONARR_1_MISSING_DAYS=7
      - VRKN_SONARR_1_MISSING_DAYS_RUN_SECONDS=300
      - VRKN_SONARR_1_FUTURE_DAYS=1
      - VRKN_SONARR_1_FUTURE_DAYS_RUN_SECONDS=300
      - VRKN_SONARR_1_QUEUE=true
      - VRKN_SONARR_1_QUEUE_RUN_SECONDS=300
      - VRKN_RADARR_1_URL=radarr1.domain.tld
      - VRKN_RADARR_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_RADARR_1_SSL=false
      - VRKN_RADARR_1_VERIFY_SSL=false
      - VRKN_RADARR_1_QUEUE=true
      - VRKN_RADARR_1_QUEUE_RUN_SECONDS=300
      - VRKN_RADARR_1_GET_MISSING=true
      - VRKN_RADARR_1_GET_MISSING_RUN_SECONDS=300
      - VRKN_OMBI_1_URL=ombi.domain.tld
      - VRKN_OMBI_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_OMBI_1_SSL=false
      - VRKN_OMBI_1_VERIFY_SSL=false
      - VRKN_OMBI_1_GET_REQUEST_TYPE_COUNTS=true
      - VRKN_OMBI_1_REQUEST_TYPE_RUN_SECONDS=300
      - VRKN_OMBI_1_GET_REQUEST_TOTAL_COUNTS=true
      - VRKN_OMBI_1_REQUEST_TOTAL_RUN_SECONDS=300
      - VRKN_OMBI_1_GET_ISSUE_STATUS_COUNTS=true
      - VRKN_OMBI_1_ISSUE_STATUS_RUN_SECONDS=300
    volumes:
      - /path/to/docker-varken/config-folder:/config
    restart: unless-stopped