version: '3.0'

volumes:
    prometheus_data: {}
    grafana_data: {}
    alertmanager_data: {}

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--query.lookback-delta=90m'
    ports:
      - "9090:9090"
    restart: unless-stopped
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - alertmanager_data:/alertmanager
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    restart: unless-stopped
  karma:
    image: lmierzwa/karma:v0.68
    container_name: karma
    environment:
      - ALERTMANAGER_URI=http://alertmanager:9093
    ports:
      - 8080:8080
    restart: unless-stopped
  
  # Exporters

  blackbox:
    image: quay.io/prometheus/blackbox-exporter:v0.17.0
    container_name: blackbox
    volumes:
      - ./blackbox/:/etc/blackboxexporter/
    command:
      - '--config.file=etc/blackboxexporter/config.yml'
    dns: 1.1.1.1
    restart: unless-stopped
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.37.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: unless-stopped
  nodeexporter:
    image: quay.io/prometheus/node-exporter:v1.0.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    restart: unless-stopped
  piholeexporter:
    image: ekofr/pihole-exporter:0.0.9
    container_name: piholeexporter
    environment:
      - PIHOLE_HOSTNAME=192.168.1.2
      - PIHOLE_PASSWORD=mypassword
      - INTERVAL=30s
      - PORT=9617
    restart: unless-stopped