version: '3.0'

volumes:
    prometheus_data: {}
    grafana_data: {}
    alertmanager_data: {}

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--query.lookback-delta=90m'
    ports:
      - "9090:9090"
    restart: unless-stopped
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - alertmanager_data:/alertmanager
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    restart: unless-stopped
  karma:
    image: lmierzwa/karma:v0.68
    container_name: karma
    environment:
      - ALERTMANAGER_URI=http://alertmanager:9093
    ports:
      - 8080:8080
    restart: unless-stopped